version: "3"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: frontend
    env_file:
      - frontend/.env
    ports:
      - "3001:3000"
